package GUI;

import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.GridLayout;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;

import javax.swing.JButton;
import javax.swing.JFrame;

import org.math.plot.Plot3DPanel;

import IO.Input;
import Regression.Controller;
import Regression.Point3D;
import Regression.Polynome;
import Regression.PolynomePool;

public class TestGUI extends javax.swing.JFrame {

	private ArrayList<Polynome> funcX;
	private ArrayList<Polynome> funcY;
	private double genauigkeit = 0.01; // user input
	private Plot3DPanel plot = new Plot3DPanel("NORTH");
	private File fileIn = new File("test\\crossvault_points.txt"); // user
																			// input
	private File fileOut = new File("C:\\Users\\Sascha\\Desktop\\output.txt"); // user
																				// input

	public TestGUI() {
		System.out.println("TestGUI");
		// create your PlotPanel (you can use it as a JPanel) with a legend at
		// SOUTH
		
		initComponents();
	}

	public void gui() {
		System.out.println("Gui");
		try {
			javax.swing.UIManager.LookAndFeelInfo[] installedLookAndFeels = javax.swing.UIManager
					.getInstalledLookAndFeels();
			for (int idx = 0; idx < installedLookAndFeels.length; idx++)
				if ("Nimbus".equals(installedLookAndFeels[idx].getName())) {
					javax.swing.UIManager.setLookAndFeel(installedLookAndFeels[idx].getClassName());
					break;
				}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(TestGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(TestGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(TestGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(TestGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>
		// </editor-fold>

		
		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {

				new TestGUI().setVisible(true);
			}
		});
	}
	
	public void update(ArrayList<Polynome> funcX2, ArrayList<Polynome> funcY2, double genauigkeit2) {
		System.out.println("update");
		funcX = funcX2;
		funcY = funcY2;
		genauigkeit = genauigkeit2;
		//TODO Bereich berechnen lassen
		double[] x = increment(0, 1.0, funcX.size()); // x = 0.0:0.1:1.0
		double[] y = increment(0, 1.0, funcY.size());// y = 0.0:0.05:1.0

		double[][] zx = fx(y);
		double[][] zy = fy(x);

		// create your PlotPanel (you can use it as a JPanel) with a legend at
		// SOUTH

		
		// add grid plot to the PlotPanel
		plot.removeAllPlots();
		plot.addGridPlot("Funktionen nach x", x, y, zx);
		plot.addGridPlot("Funktionen nach y", x, y, zy);
	}
	
	public double fx(Double[] f, double y) {
		double z = 0;
		double exp;

		for (int i = 0; i < f.length; i++) {
			exp = f.length - i - 1;
			z += f[i] * Math.pow(y, exp);
		}

		return z;
	}

	public double fy(Double[] f, double x) {
		double z = 0;
		double exp;

		for (int i = 0; i < f.length; i++) {
			exp = f.length - i - 1;
			z += f[i] * Math.pow(x, exp);
		}

		return z;
	}

	public double[][] fx(double[] y) {
		double[][] z = new double[funcX.size()][funcX.size()];
		for (int i = 0; i < funcX.size(); i++) {

			for (int j = 0; j < funcX.size(); j++) {
				z[i][j] = funcX.get(i).function(y[j]);
			}
		}
		return z;
	}

	public double[][] fy(double[] x) {
		double[][] z = new double[funcY.size()][funcY.size()];
		for (int i = 0; i < funcY.size(); i++) {
			for (int j = 0; j < funcY.size(); j++) {
				z[j][i] = funcY.get(i).function(x[j]);
			}
		}
		return z;
	}

	public double[] increment(double start, double step, double end) {
		double range = end - start;
		int steps = (int) (range / step);
		double[] rv = new double[steps];
		for (int i = 0; i < steps; i++) {
			rv[i] = start + (step * i);
		}
		return rv;
	}
	
	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {
System.out.println("Init");
		jPanel1 = new javax.swing.JPanel();
		jPanel2 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		jTextField1 = new javax.swing.JTextField();
		jTextField4 = new javax.swing.JTextField();
		jTextField5 = new javax.swing.JTextField();
		jLabel2 = new javax.swing.JLabel();
		jButton1 = new javax.swing.JButton();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		jButton2 = new javax.swing.JButton();
		jLabel5 = new javax.swing.JLabel();
		jLabel6 = new javax.swing.JLabel();
		jLabel7 = new javax.swing.JLabel();
		jLabel8 = new javax.swing.JLabel();
		jScrollPane1 = new javax.swing.JScrollPane();
		jTextArea1 = new javax.swing.JTextArea();
		jScrollPane2 = new javax.swing.JScrollPane();
		jTextArea2 = new javax.swing.JTextArea();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setTitle("Plot");

		/*
		 * Plot
		 */
		jPanel1.setSize(new java.awt.Dimension(700, 500));

		BorderLayout bl = new BorderLayout(0, 0);
		jPanel1.setLayout(bl);

		plot.setPreferredSize(new Dimension(700, 500));
		jPanel1.add(plot, BorderLayout.CENTER);

		/*
		 * Plot Ende
		 */

		/*
		 * User Interface
		 */

		jPanel2.setName("User Interface"); // NOI18N
		jPanel2.setPreferredSize(new java.awt.Dimension(700, 250));

		jLabel1.setText("Genauigkeit:");

		jTextField1.setText(String.valueOf(genauigkeit));

		jLabel2.setText("Input:");

		// TODO
		jLabel3.setText("FI");

		jLabel4.setText("Fl�cheninhalt");

		jButton2.setText("Neu Berechnen");
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});

		jLabel5.setText("Output:");

		jLabel7.setText("Polynome in x-Richtung");

		jLabel8.setText("Polynome in y-Richtung");

		// TODO add polynom-equations
		jTextArea1.setColumns(20);
		jTextArea1.setRows(5);
		jScrollPane1.setViewportView(jTextArea1);

		jTextArea2.setColumns(20);
		jTextArea2.setRows(5);
		jScrollPane2.setViewportView(jTextArea2);

		jTextField4.setText(fileIn.getAbsolutePath());

		jTextField5.setText(fileOut.getAbsolutePath());

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout.setHorizontalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel2Layout.createSequentialGroup().addContainerGap()
						.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addGroup(jPanel2Layout.createSequentialGroup().addComponent(jButton2).addGap(0, 0,
								Short.MAX_VALUE))
						.addGroup(jPanel2Layout.createSequentialGroup().addComponent(jLabel1)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addComponent(jTextField1)).addComponent(jTextField4).addComponent(jTextField5))
						.addGap(36, 36, 36)
						.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(jLabel7).addComponent(jScrollPane1,
										javax.swing.GroupLayout.PREFERRED_SIZE, 235,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(38, 38, 38)
						.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(jLabel8).addComponent(jScrollPane2,
										javax.swing.GroupLayout.PREFERRED_SIZE, 235,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(16, 16, 16)));
		jPanel2Layout.setVerticalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel2Layout.createSequentialGroup().addContainerGap()
						.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel7).addComponent(jLabel8))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(jPanel2Layout
								.createParallelGroup(
										javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(jPanel2Layout.createSequentialGroup().addGap(2, 2, 2)
										.addGroup(jPanel2Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel1)
												.addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(9, 9, 9).addComponent(jLabel2).addGap(4, 4, 4)
										.addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(jLabel5)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(jButton2).addGap(4, 4, 4).addComponent(jLabel4)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(jLabel3).addGap(35, 35, 35))
								.addGroup(jPanel2Layout.createSequentialGroup()
										.addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 225,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
								.addGroup(jPanel2Layout.createSequentialGroup()
										.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 225,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addContainerGap()))));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addContainerGap()
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addGroup(layout.createSequentialGroup()
								.addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(0, 0, Short.MAX_VALUE)))
						.addContainerGap()));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				javax.swing.GroupLayout.Alignment.TRAILING,
				layout.createSequentialGroup().addContainerGap()
						.addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
								javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(25, 25, 25)));

		pack();
	}// </editor-fold>

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		System.out.println("Update");
		Controller.update(fileIn, genauigkeit, this);
	}

	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JScrollPane jScrollPane2;
	private javax.swing.JTextArea jTextArea1;
	private javax.swing.JTextArea jTextArea2;
	private javax.swing.JTextField jTextField1;
	private javax.swing.JTextField jTextField4;
	private javax.swing.JTextField jTextField5;
	// End of variables declaration

}
